// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}